### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Walleeeda** [3MAH/microgen#17]
When I try the code in the documentary https://microgen.readthedocs.io/en/latest/examples/tpms.html  
it throw an error
AttributeError: module 'microgen.shape.tpms' has no attribute 'neovius'
I noticed that the code in github is fine, and it may because the documentary is not update.
Thanks for your contribute

**Comment by chemiskyy** [comment]
Thanks for your comment, the documentation is currently outdated, please see : 
#16

**Comment by kmarchais** [comment]
Hello, as @chemiskyy said the documentation is outdated, we are currently updating it.

Here is the temporary link for the doc: https://microgen.readthedocs.io/en/fix_doc/examples/tpms.html

Here is the code you need for the `neovius` shape:
```
from microgen import Tpms
from microgen.shape.surface_functions import neovius

geometry = Tpms(
    surface_function=neovius,
    offset=0.3,
    resolution=30,
)
shape = geometry.generateVtk(type_part="sheet").extract_surface()
shape.save("gyroid.stl")
```

**Comment by Walleeeda** [comment]
very thanks
