### ISSUE TITLE
Issue on RasterGyroid script

### ISSUE THREAD

**Issue by sudeep5511** [3MAH/microgen#2]
Hello,
The script is showing error.
Attached is the error message
![Error_rasterGyroid](https://user-images.githubusercontent.com/87186102/159806996-9971946c-bc87-4e3e-bd2a-f8b0b75f3ae0.png)

The script is searching for the data folder and its content (tpms_minus.stl, tpms_plus.stl, tpms_testminus.stl, tpms_testplus.stl) in order to execute.

**Comment by chemiskyy** [comment]
Hi Sudeep the API has changed a bit, but the new example is now working fine
