### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by nicoguaro** [3MAH/microgen#4]
I tried to install ``microgen`` on Windows but I could not succeed, I think that it is because ``neper`` is not available for Windows on conda-forge. I also tried to run ``microgen`` on Binder but it does not work either.

**Comment by kmarchais** [comment]
Hello, thanks for the feedback, I'm working on it. Indeed, it's a problem with dependencies on Windows.

**Comment by kmarchais** [comment]
You should now be able to install microgen on Windows with conda : `conda install -c conda-forge -c cadquery -c set3mah microgen`

**Comment by kmarchais** [comment]
The update that I did removed neper dependency even when installing from Linux or MacOS, I fixed this by creating a specific package for each platform.
I also added a binder badge to the readme so you can run the specific notebook examples of microgen.

**Comment by nicoguaro** [comment]
I tried both, the local installation on Windows and the remote use on Binder, and they are working. Thanks!
