### ISSUE TITLE
tuple type not subscriptable

### ISSUE THREAD

**Issue by EGajetti** [3MAH/microgen#6]
Hello, I'm trying to use your module to create TPMS.
I'm using python 3.8.8 on Windows,  I have installed all the requirements.
I have run the script "examples/TPMS/gyroid/gyroid.py" . It gives me the following error:

  File ~\anaconda3\lib\site-packages\microgen\shape\basicGeometry.py:26 in BasicGeometry
    center: tuple[float, float, float] = (0, 0, 0),

TypeError: 'type' object is not subscriptable

How can I fix this? 
Thanks in advance,
Eleonora

**Comment by kmarchais** [comment]
Hello, I think these python typing hints are not working with python < 3.9.
Is it possible for you to try with a newer python version?

Kevin

**Comment by kmarchais** [comment]
I have vtk=9.1.0 installed, have you installed it with pip?
If you know about conda, I suggest you to install microgen with conda : 
`conda install -c conda-forge -c cadquery -c set3mah microgen`

I will have a look at this issue with vtk

**Comment by EGajetti** [comment]
When I try using the conda command, it is not able to actually install microgen:

I type: 

>conda install -c conda-forge -c cadquery -c set3mah microgen

and the output:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

And it goes on like that

**Comment by kmarchais** [comment]
Is it in an empty environment?
I suggest to do it in a clean environment to avoid conflict between dependencies.

To do so : 
`conda create -n microgen`
`conda activate microgen`
`conda install -c conda-forge -c cadquery -c set3mah microgen`

It is possible that it fails a few times but it should install it successfully in the end.

**Comment by EGajetti** [comment]
I managed to make it work, thank you.
The problem was caused by spyder, which had some inconsistencies with microgen.
Thank you for your time,
Eleonora

**Comment by EGajetti** [comment]
Hello, I have tried to use your module also on WSL2, running ubuntu 20.04. 
In this case, I cannot use conda, and I face the same problem I had before on windows with vtk, i.e. the version you specify in the requirements cannot be installed, neither any versions below 9.2.0, which give problems as I already reported for windows.

**Comment by kmarchais** [comment]
Yes it seems that we have an issue with pip and vtk unfortunately, I will work on it as soon as I can

**Comment by EGajetti** [comment]
Anyway, found that vtk=2.2.2 works fine.
Thank you !

**Comment by kmarchais** [comment]
Issues with vtk and pip have been solved with PR #8, it is now possible to install microgen with pip (and even on Windows).
